import uuid
from typing import Any

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base
from app.models.base import TimestampMixin, UUIDPrimaryKeyMixin


class QueryHistory(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """An append-only log of every SQL query actually run against a
    dataset — whether typed directly in the SQL Explorer or generated by
    the AI Analyst's Natural Language to SQL path. Deliberately a plain
    log, not a "favorite"-flagged table — SavedQuery (below) is the
    explicit, deliberate "promote this" action, matching how Insight
    already works as an explicit save rather than an auto-flagged
    history entry (see docs/V2_DATABASE_PLAN.md's reasoning)."""

    __tablename__ = "query_history"

    owner_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    dataset_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("datasets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Null when this came from the AI Analyst's structured-query path
    # (app.ai.analyst) rather than SQL — that path doesn't produce SQL
    # text, so there's nothing to log here beyond the question itself.
    question: Mapped[str | None] = mapped_column(Text, nullable=True)
    sql_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    # {"columns": [...], "row_count": int, "truncated": bool} — not the
    # full result set, which could be large and is always reproducible by
    # re-running sql_text against the dataset's current state.
    result_meta: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    # "ai_sql" | "sql_explorer" | "ai_structured" | "ai_deep_analysis"
    source: Mapped[str] = mapped_column(String(32), nullable=False)

    def __repr__(self) -> str:  # pragma: no cover - debug aid only
        return f"QueryHistory(id={self.id}, source={self.source!r})"


class SavedQuery(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """An explicitly named, reusable SQL query — distinct from
    QueryHistory (automatic) and from Insight (which pairs a query with
    an AI-written answer, not just the query itself)."""

    __tablename__ = "saved_queries"

    owner_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    dataset_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("datasets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    sql_text: Mapped[str] = mapped_column(Text, nullable=False)

    def __repr__(self) -> str:  # pragma: no cover - debug aid only
        return f"SavedQuery(id={self.id}, name={self.name!r})"
